Namespace(batch_size=8000, cpuonly=False, dataset='imagenet', downloadall=False, end=10000, freeze=True, freeze_idx=11, manual_split=False, model='resnet18', num_epochs=1, sequential=False, split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (resnet18) till index 11
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Memory occpied: (1168.0, 3.0)
Read 994.2840633392334 MBs for this batch
Streaming imagenet data took 60.5951714515686 seconds

Epoch: 0
Time of next(dataloader) is: 28.741915702819824
Time for copying to cuda: 1.2430546283721924
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 249, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 232, in _forward_impl
    x = self.conv1(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 11.96 GiB (GPU 0; 14.76 GiB total capacity; 4.53 GiB already allocated; 9.12 GiB free; 4.55 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (1168.0, 3478.0)
Read 1030.153896331787 MBs for this batch
Streaming imagenet data took 57.80778193473816 seconds
