Namespace(batch_size=1000, cpuonly=False, dataset='inaturalist', downloadall=False, end=10000, freeze=True, freeze_idx=36, model='vgg19', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vgg19) till index 36
The mode is:  vanilla
Memory occpied: (1934.0, 3.0)
Memory occpied: (1934.0, 3.0)
Memory occpied: (1934.0, 3.0)
Memory occpied: (1934.0, 3.0)
Read 265.7877779006958 MBs for this batch
Streaming inaturalist data took 4.762917757034302 seconds
The mode is:  vanilla

Epoch: 0
Time of next(dataloader) is: 4.795769929885864
Time for copying to cuda: 0.15129375457763672
Read 266.2351598739624 MBs for this batch
Streaming inaturalist data took 5.10673451423645 seconds
Time for forward pass: 32.18277597427368
Time for backpropagation: 0.28405022621154785
GPU memory for training: 26.599037647247314                          

Memory occpied: (1934.0, 3.0)
One training iteration takes: 37.629825830459595 seconds
Index: 0
Then, training+dataloading take 37.632721185684204 seconds
The mode is:  vanilla

Epoch: 0
Memory occpied: (5596.0, 11418.0)
Memory occpied: (5596.0, 11418.0)
Memory occpied: (5596.0, 11418.0)
Time of next(dataloader) is: 4.925452947616577
Time for copying to cuda: 0.14983153343200684
Memory occpied: (11720.0, 14488.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/vgg.py", line 66, in forward
    x = self.features(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 447, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: CUDA out of memory. Tried to allocate 5.98 GiB (GPU 0; 14.76 GiB total capacity; 8.33 GiB already allocated; 3.31 GiB free; 10.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Read 259.5968008041382 MBs for this batch
Streaming inaturalist data took 6.016659498214722 seconds
The whole process took 56.30530881881714 seconds
