Namespace(batch_size=2000, cpuonly=False, dataset='inaturalist', downloadall=False, end=10000, freeze=True, freeze_idx=17, model='vit', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (vit) till index 17
The mode is:  vanilla
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Read 532.0228118896484 MBs for this batch
Streaming inaturalist data took 14.751960515975952 seconds
The mode is:  vanilla

Epoch: 0
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Memory occpied: (1654.0, 3.0)
Time of next(dataloader) is: 9.039751529693604
Time for copying to cuda: 0.31031346321105957
Memory occpied: (2804.0, 740.0)
Memory occpied: (2804.0, 1182.0)
Memory occpied: (2804.0, 1644.0)
Memory occpied: (13890.0, 3356.0)
Read 524.3110990524292 MBs for this batch
Streaming inaturalist data took 14.88761568069458 seconds
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 433, in forward
    x = self.forward_features(x)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 421, in forward_features
    x = self.blocks(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 238, in forward
    x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x))))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timm/models/vision_transformer.py", line 199, in forward
    attn = (q @ k.transpose(-2, -1)) * self.scale
RuntimeError: CUDA out of memory. Tried to allocate 1.74 GiB (GPU 0; 14.76 GiB total capacity; 12.23 GiB already allocated; 1.19 GiB free; 12.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (13896.0, 15060.0)
The whole process took 38.161434173583984 seconds
