Namespace(batch_size=2000, cpuonly=False, dataset='inaturalist', downloadall=False, end=10000, freeze=True, freeze_idx=21, model='resnet50', num_epochs=1, sequential=False, split_choice='automatic', split_idx=100, start=0, testonly=False, use_intermediate=False)
==> Preparing data..
==> Building model..
Using split index: 100
Freezing the lower layers of the model (resnet50) till index 21
The mode is:  vanilla
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Read 532.0228118896484 MBs for this batch
Streaming inaturalist data took 13.367754459381104 seconds
The mode is:  vanilla

Epoch: 0
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Memory occpied: (1430.0, 3.0)
Time of next(dataloader) is: 8.781451940536499
Time for copying to cuda: 0.3006424903869629
Memory occpied: (2580.0, 792.0)
Memory occpied: (2580.0, 1272.0)
Memory occpied: (2580.0, 1730.0)
Read 524.3110990524292 MBs for this batch
Streaming inaturalist data took 14.1348237991333 seconds
Memory occpied: (12692.0, 12098.0)
Exception: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 283, in forward
    return self._forward_impl(x)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 271, in _forward_impl
    x = self.layer1(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torchvision/models/resnet.py", line 156, in forward
    identity = self.downsample(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/functional.py", line 2421, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 2.99 GiB (GPU 0; 14.76 GiB total capacity; 8.00 GiB already allocated; 2.36 GiB free; 11.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Memory occpied: (2592.0, 12098.0)
The whole process took 35.760138511657715 seconds
